name: Build packages

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-formatting:
    name: Check formatting
    runs-on: [self-hosted, linux, X64, normie]
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Run format check
        run: nix develop --command nixpkgs-fmt --check .

  evaluate-flake:
    name: Evaluate flake
    runs-on: [self-hosted, linux, X64, normie]
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Check flake evaluation
        run: nix flake check --no-build --show-trace

  build-checks-arm:
    name: Build aarch64-linux checks
    runs-on: [self-hosted, linux, arm64]
    needs: evaluate-flake
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - uses: cachix/cachix-action@v16
        with:
          name: specter-co
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Evaluate and build aarch64-linux checks
        run: |
          nix build .#checks.aarch64-linux.orangepi-5 --no-link --show-trace
          nix build .#checks.aarch64-linux.orangepi-5-plus --no-link --show-trace
